### ISSUE TITLE
'Note' column only displays numeric characters

### ISSUE THREAD

**Issue by buckrogerss** [FrozenTundraTrader/sierrachart#10]
This may be a feature but the presence of any text/alpha characters in the 'Note' column displays nothing in the label in SC. Numeric values display normally.

**Comment by FrozenTundraTrader** [comment]
@buckrogerss please provide the URL to your spreadsheet, I will take a look and try to reproduce on my end.  First I've heard of an issue like this.

**Comment by buckrogerss** [comment]
hey, thanks for getting back to me. in looking back over this today, I found the issue, and it appears to be the sheet auto-formatting. all the values I have been using in 'Note' are currently numbers, and even though they're converted to strings in python, google sheets converts them back to numbers, even with leading/trailing spaces or a leading apostrophe. for some reason, if there are x number of number-formatted values in the column, it won't output the text-formatted value in SC. if I have all alpha-based strings in Note, it works fine.

link to a sheet I'm using: https://docs.google.com/spreadsheets/d/1W7d1pZ6R97WnrbBmg0laZyNL4xuTHkdpVsyhlYK2RZg/edit?usp=sharing

**Comment by FrozenTundraTrader** [comment]
Souds good, thanks for closing the loop. Closing out this issue.
