### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Neophema** [FrozenTundraTrader/sierrachart#5]
I am on SC 2443 and this study is great. I've grown very dependent on it. Unfortunately, task-manager shows it growing incrementally until it causes Sierra Chart to crash. 

Someone far wiser than I told me the GDI Objects increment until it exceeds the memory allowed.

**Comment by FrozenTundraTrader** [comment]
Hi @Neophema - which study file are you referring to? I'll take a look.

**Comment by Neophema** [comment]
Thank you.  It's the google_sheets_importer.scsf_GoogleSheetsLevelsImporter. 

I thought there might be a conflict with another study so I generated a plain chart and added the one study for GoogleSheetsLevelsImporter. It still increments the GDI object.  The GDI typically bounced between 200 and 300 but it hits 2000 in about ten minutes.

**Comment by FrozenTundraTrader** [comment]
I need to update the cpp file for that study.  Don't use the Visual Studio files for it, try compiling it using the raw `.cpp` file and using **Remote Build** in SC.  I'll update the cpp file in a second here.

**Comment by FrozenTundraTrader** [comment]
Here you go:
https://github.com/FrozenTundraTrader/sierrachart/blob/main/google_sheets_importer.cpp

**Comment by Neophema** [comment]
Thank you! 
It appears to have a error?


15:02:55
Allow time for the server to compile the files and build the DLL.
None of the selected source files contains the SCDLLName() line at the top of the file. Refer to ACSIL documentation.-- End of Build --     15:02:55


    On Wednesday, November 16, 2022 at 01:41:37 PM CST, Frozen Tundra ***@***.***> wrote:  
 
 


Here you go:
https://github.com/FrozenTundraTrader/sierrachart/blob/main/google_sheets_importer.cpp

**Comment by FrozenTundraTrader** [comment]
Can you double check you've selected the correct file to compile?  You've updated the file in your SC studies directory?  I can see the SCDLLName in GitHub with the link I shared with you, on line 5
![image](https://user-images.githubusercontent.com/96592245/202462930-6901c078-0111-4434-b2c0-8f00727743b3.png)

**Comment by Neophema** [comment]
Will do. Thank you again. 
    On Thursday, November 17, 2022 at 07:47:28 AM CST, Frozen Tundra ***@***.***> wrote:  
 
 


Can you double check you've selected the correct file to compile? You've updated the file in your SC studies directory? I can see the SCDLLName in GitHub with the link I shared with you, on line 5

**Comment by Neophema** [comment]
This is a new bug report. I appreciate your help. 

It's still incrementing the "GDI objects". 

I did not open any of my chart-books, I generated a new chart-book and created a chart with no studies. I loaded the google_sheets_importer study. I didn't change the configuration, just applied it. I could see drawings/levels on the chart imported from your default sheet. 

The GDI value (second instance) normally hovers around the mid 200's but once the importer study is loaded it starts to increment GDI's and as mentioned, hits 1000 in a few minutes. After twenty or thirty minutes the screen starts flashing and Sierra cannot be shut down, it has to be killed. 

I upgraded SC to 2457 and it didn't help. On a whim, I hid the study. The levels in the spreadsheet still show in the chart but the GD objects slowed down significantly.  Iit may be incrementing but it is very slowly.

**Comment by FrozenTundraTrader** [comment]
Hi @Neophema - thanks for this update, I will start looking into this.

**Comment by FrozenTundraTrader** [comment]
@Neophema can you try the latest commit and see if this helps at all?
https://github.com/FrozenTundraTrader/sierrachart/blob/main/google_sheets_importer.cpp

**Comment by Neophema** [comment]
Thank you. It is behaving better. I will leave it up for this weekend and see how it does. I'll report Monday.

**Comment by Neophema** [comment]
It no longer appears to have a memory leak - THANK YOU. 

It does appear to be intolerant of blank rows. I use clusters of rows for things like swings lows, highs, centuries, etc. It's a visual organization for the spreadsheet. Previous version ignored blank rows (or blank cells A & B) but now blank rows seem to affect it. Not 100%, as some populated rows that follow a blank row are picked up but inconsistently.

**Comment by Neophema** [comment]
No, I was mistaken. I had some notes in column i forward and that seems to have affected the process. 

I'll triple check it today and report back this afternoon.

**Comment by Neophema** [comment]
Well it worked fine all day. 

I had notes on the side (Column "I") to the right. I think that was corrupting the study. At first it looked like a rollover influence but I realized that was impossible.

**Comment by FrozenTundraTrader** [comment]
Fantastic.  Thanks for the update.

**Comment by Neophema** [comment]
This is not a new incident, just reporting.  I suspect this is a Sierra Issue, not entirely your code. 

If I leave my Sierra running, the levels disappear during the week. Sometimes they come back if I an open any study and hit ok. If Sierra is still open from my weekend homework, I have to shut down completely and reload Sierra to get them back on Monday.

One other thing I noticed: if for some reason I open and close "studies", the levels go away. If I immediately open and close "studies" they usually come back.  

I am running 2457.
