### ISSUE TITLE
Pace of tape study draws under some studies

### ISSUE THREAD

**Issue by GardnerCode** [FrozenTundraTrader/sierrachart#6]
Great work on the pace of tape study.  A minor issue I'm having is some background coloring at price (non transparent) draws over the PoT study even when PoT is placed at the bottom of the study order and "Draw Study Underneath Main Price Graph" is not checked.

I have tried adding `sc.DrawACSDrawingsAboveOtherDrawings=1;` to the defaults code and this did not fix the issue.

https://user-images.githubusercontent.com/76569695/203483087-7e95ff39-16c8-4647-adaf-94f2a69a1008.mp4

**Comment by FrozenTundraTrader** [comment]
Hi @GardnerCode , thanks for this, I will take a look this week.

**Comment by FrozenTundraTrader** [comment]
@GardnerCode - After reviewing your video, I wonder if the other study that is blocking the Pace of Tape study is not using drawing tools via code, but rather the WinGDI libraries **to draw on top** of everything...
Can you try to draw something with a new drawing tool like Line or Text through that area?  Same thing happen?

**Comment by GardnerCode** [comment]
Thanks for the reply, the study is Volume At Price Threshold Alert V2 and the culprit is the extension lines subgraph.  (Set to draw study underneath main price graph)  

I checked drawing with some tools there, weirdly the lines draw on top but a rectangle draws underneath.  I think then the issue is with Sierra Chart and that study subgraph?  Strange!

![image](https://user-images.githubusercontent.com/76569695/204387344-004a541e-8bc7-4e53-a2db-e3d981c3c18c.png)

**Comment by GardnerCode** [comment]
Ok looked into it some more, there is a drawing setting for that in the chart settings window documented here:  https://www.sierrachart.com/index.php?page=doc/ChartSettings.html#DrawHighlightDrawingsUnderneath

Setting this to No fixes the Pace of Tape and rectangles drawing under the background coloring.  
![image](https://user-images.githubusercontent.com/76569695/204391332-47ed5544-ee5a-481a-8498-f2718c6389a2.png)
